# Generated by Django 5.1.4 on 2024-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='gpa',
        ),
        migrations.AddField(
            model_name='documents',
            name='gpa_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='student_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
