# Generated by Django 5.1.4 on 2024-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0002_remove_documents_gpa_documents_gpa_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(default='transcript', max_length=30),
        ),
    ]
