# Generated by Django 5.1.4 on 2024-12-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0003_rsa_alter_documents_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
