# Generated by Django 5.1.4 on 2024-12-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0004_documents_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Ali\\Desktop\\SecNewProject\\osds\\osds_app\\documents'),
        ),
    ]
