# Generated by Django 5.1.4 on 2024-12-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0008_documents_is_verified_documents_rsa_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='rsa_key',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='rsa',
            name='is_active',
        ),
    ]
