# Generated by Django 5.1.4 on 2024-12-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0009_remove_documents_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
