# Generated by Django 5.1.4 on 2024-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0010_documents_digital_signature_documents_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='digital_signature',
        ),
        migrations.AddField(
            model_name='documents',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='signature_data',
            field=models.TextField(null=True),
        ),
    ]
