# Generated by Django 5.1.4 on 2024-12-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0011_remove_documents_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_receipt_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='./documents/receipts/'),
        ),
    ]
