# Generated by Django 5.1.4 on 2024-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0012_documents_is_receipt_verified_documents_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='receipt_signature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='receipt_signature_data',
            field=models.TextField(null=True),
        ),
    ]
