# Generated by Django 5.1.4 on 2024-12-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osds_app', '0013_documents_receipt_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='./documents/docs/'),
        ),
    ]
